CREATE TABLE item_user (
 id        BIGSERIAL    NOT NULL PRIMARY KEY,
 item_id   BIGINT      NOT NULL UNIQUE,
 user_id   BIGINT      NOT NULL UNIQUE,
 type      VARCHAR(64) NOT NULL UNIQUE,
 create_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
 update_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
)
